#!/usr/bin/env bash
# Vendor the canonical tables and crate version into this package before
# packing. The repository keeps no duplicates: `tables/` and `Cargo.toml`
# at the cgrade root stay canonical; `src/generated/` is regenerated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/src/generated" "$ROOT/typst/generated" "$ROOT/py/cgrade"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$ROOT" "$VERSION" <<'EOF'
import json
import sys

here, root, version = sys.argv[1], sys.argv[2], sys.argv[3]
with open(f"{root}/tables/grades.json", encoding="utf-8") as handle:
    grades = json.load(handle)
out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const GRADES_TABLE: unknown = {json.dumps(grades, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/tables.ts", "w", encoding="utf-8") as handle:
    handle.write(out)


def typst_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def typst_num(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return f"{value}.0"
    return repr(float(value))


def typst_entry(key, entry):
    fields = [
        f"best: {typst_num(entry['best'])}",
        f"worst: {typst_num(entry['worst'])}",
        f"pass: {typst_num(entry['pass'])}",
        f"step: {typst_str(entry['step'])}",
        f"higher_is_better: {typst_num(entry['higher_is_better'])}",
    ]
    body = ",\n      ".join(fields)
    return f"{typst_str(key)}: (\n      {body},\n    )"


entries = ",\n    ".join(
    typst_entry(key, entry) for key, entry in grades["scales"].items()
)
supported = "(" + ", ".join(typst_str(item) for item in grades["supported"]) + ")"
typ = (
    "// GENERATED by js/@corbet-foss/cgrade/scripts/sync-assets.sh — do not edit.\n"
    "#let grades-table = (\n"
    f"  scales: (\n    {entries},\n  ),\n"
    f"  supported: {supported},\n"
    ")\n"
)
with open(f"{root}/typst/generated/grades.typ", "w", encoding="utf-8") as handle:
    handle.write(typ)
print(f"synced tables/grades.json, version {version}")
EOF

python3 "$ROOT/scripts/sync-python.py"
