schema = 1

[github]
repository = "corbet-foss/cgrade"
workflow = "ccid.yml"
workflow_sha256 = "aeaa1607da5ab26fe8562661c3855778333cba4c7e2477e78edc2a1cc4e4b7a1"
checks = ["rust"]
platform = "linux-x86_64"
secret_free = true
free_eligible = true
tool_revision = "27c248aefa3c7198be6716a884d290c717774b21"
tool_bootstrap_workflow = "bootstrap.yml"
tool_bootstrap_sha256 = "d275261db8126e8d579184024a9eb4eaeedb15fcb7801804697d396c48e391ae"

[dependencies]
files = ["Cargo.lock", "Cargo.toml"]
